name = "LoggingTestSets"
uuid = "c2339e6d-2e7f-4cf9-92d2-844738085fb8"
authors = ["notinaboat <notinaboat@icloud.com>"]
version = "0.1.0"

[deps]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
